import React from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Bell,
  Play,
  MapPin,
  CheckCircle2,
  AlertCircle,
  Tag,
  Clock,
  Sparkles,
  ArrowLeft,
  Volume2
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { voiceService } from '../services/voiceService';

export const NotificationsPage: React.FC = () => {
  const navigate = useNavigate();
  const { notifications, markNotificationRead, updateMissionItemStatus, activeMission, language } = useApp();

  const handlePlayVoice = (text: string) => {
    voiceService.speak(text, language);
  };

  const handleMarkFound = (notifId: string, productId?: string) => {
    markNotificationRead(notifId);
    if (activeMission && productId) {
      const match = activeMission.items.find(i => i.product_id === productId);
      if (match) {
        updateMissionItemStatus(activeMission.id, match.id, 'found');
      }
    }
  };

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-slate-950 text-white p-4 sm:p-8">
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Header (Matching Screen 9) */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate(-1)}
              className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 hover:text-white hover:bg-slate-800 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
            </button>
            <div>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white flex items-center gap-2">
                Proactive Assistant
                <span className="text-xs font-semibold text-emerald-400 bg-emerald-950/80 px-2.5 py-1 rounded-full border border-emerald-500/30">
                  {notifications.filter(n => !n.read).length} unread
                </span>
              </h1>
              <p className="text-xs text-slate-400 mt-0.5">
                Contextual in-store guidance generated by the Customer Agent
              </p>
            </div>
          </div>
        </div>

        {/* Notifications List (Matching Screen 9) */}
        <div className="space-y-4">
          {notifications.map((notif) => {
            return (
              <div
                key={notif.id}
                className={`p-5 rounded-2xl border transition-all ${
                  notif.read
                    ? 'bg-slate-900/60 border-slate-800/80'
                    : 'bg-slate-900 border-emerald-500/40 shadow-xl shadow-emerald-500/5 ring-1 ring-emerald-500/20'
                }`}
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3.5">
                    <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center shrink-0 mt-0.5">
                      <Bell className="w-5 h-5" />
                    </div>
                    <div>
                      <h3 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
                        {notif.title}
                        {!notif.read && (
                          <span className="w-2 h-2 rounded-full bg-emerald-400" />
                        )}
                      </h3>
                      <p className="text-xs sm:text-sm text-slate-300 mt-1 leading-relaxed">
                        {notif.message}
                      </p>
                    </div>
                  </div>

                  <span className="text-[11px] text-slate-400 shrink-0 flex items-center gap-1 font-mono">
                    <Clock className="w-3 h-3 text-slate-500" />
                    {notif.created_at}
                  </span>
                </div>

                {/* Notification Action Buttons (Screen 9) */}
                <div className="flex flex-wrap items-center gap-2 mt-4 pt-3 border-t border-slate-800/80">
                  {/* Play Voice Button */}
                  <button
                    onClick={() => {
                      markNotificationRead(notif.id);
                      handlePlayVoice(`${notif.title}. ${notif.message}`);
                    }}
                    className="px-3.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 rounded-xl flex items-center gap-1.5 transition-colors border border-slate-700 cursor-pointer"
                  >
                    <Play className="w-3.5 h-3.5 text-emerald-400 fill-emerald-400" />
                    <span>Play</span>
                  </button>

                  {/* View Location Button */}
                  {notif.product_id && (
                    <button
                      onClick={() => {
                        markNotificationRead(notif.id);
                        navigate(`/customer/map?product=${notif.product_id}`);
                      }}
                      className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-500 text-xs font-semibold text-white rounded-xl flex items-center gap-1.5 transition-colors shadow-sm cursor-pointer"
                    >
                      <MapPin className="w-3.5 h-3.5" />
                      <span>View Location</span>
                    </button>
                  )}

                  {/* Mark Found Button */}
                  <button
                    onClick={() => handleMarkFound(notif.id, notif.product_id)}
                    className="px-3.5 py-1.5 bg-emerald-500 hover:bg-emerald-400 text-xs font-bold text-slate-950 rounded-xl flex items-center gap-1.5 transition-colors shadow-sm cursor-pointer"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Mark Found</span>
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
